# Generated by Django 4.1.7 on 2023-04-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
    ]
