# Generated by Django 4.1.7 on 2023-03-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_message_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='likes',
        ),
    ]
